services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/var/www/html
    environment:
      VIRTUAL_HOST: ledger.localhost
      AWS_ACCESS_KEY_ID: 'test'
      AWS_SECRET_ACCESS_KEY: 'test'
    expose:
      - 80
    networks:
      - reverse-proxy
      - default

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"

networks:
  reverse-proxy:
    external: true
