services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/var/www/html
    ports:
      - "8081:8080"
    networks:
      - reverse-proxy
      - default

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ledger
      POSTGRES_PASSWORD: ledger
      POSTGRES_USER: ledger

networks:
  reverse-proxy:
    external: true
