parameters:
  ledger.apiKey: '%env(base64:LEDGER_API_KEY)%'
  ledger.privateKey: '%env(base64:LEDGER_SIGNATURE_PRIVATE_KEY)%'
  ledger.publicKey: '%env(base64:LEDGER_SIGNATURE_PUBLIC_KEY)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Security\ApiKeyAuthenticator:
    arguments:
      $apiKey: '%ledger.apiKey%'

  App\Service\Blockchain:
    arguments:
      $privateKey: '%ledger.privateKey%'
      $publicKey: '%ledger.publicKey%'